### ISSUE TITLE
[Editor] Changing the name of the story part breaks the story part editing view

### ISSUE THREAD

**Issue by warpfox** [tommcgurl/choose-your-own-adventure-builder#77] opened 2019-08-27 15:30 UTC
When you edit the name of the story part and click save, you get a "cannot find property of undefined" error.

I am assuming that since the storyPartKey gets changed but not updated inside the component, it's trying to find the old key that isn't there.

**Comment by VirtuaBoza** [comment] 2019-08-29 22:00
This is prolly a dupe of #34

**Comment by VirtuaBoza** [comment] 2019-08-29 22:01
This is a dupe of #34

**Closed by VirtuaBoza** 2019-08-29 22:01 UTC
Labels: bug
